name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "selenium-test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Running selenium tests
        run: docker run $IMAGE
